import React from "react";

type Props = {
    zasekiID: (zaseki: string) => void;
};

export const ZasekiSelect= (
    {zasekiID}:Props ,
)=> {
    const getzaseki=(zaseki:string)=> {
        // console.log(zaseki);
        zasekiID(zaseki);
    }

    return (
        <div>
            <table className="table-select">
                <thead>
                    <tr>
                        <th> </th>
                        <th>A</th>
                        <th>B</th>
                        <th>C</th>
                        <th>D</th>
                        <th>E</th>
                        <th>F</th>
                        <th>G</th>
                        <th>H</th>
                        <th>I</th>
                        <th>J</th>
                        <th>K</th>
                        <th>L</th>
                        <th>M</th>
                        <th>N</th>
                        <th>O</th>
                        <th>P</th>
                        <th>Q</th>
                        <th>R</th>
                        <th>S</th>
                        <th>T</th>
                        <th>U</th>
                        <th>V</th>
                        <th>W</th>
                        <th>X</th>
                        <th>Y</th>
                        <th>Z</th>
                        <th>AA</th>
                        <th>AB</th>
                        <th>AC</th>
                        <th>AD</th>
                        <th>AE</th>
                        <th>AF</th>
                        <th>AG</th>
                        <th>AH</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("H1")}
                            >
                                H1
                            </button>
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("I1")}
                            >
                                I1
                            </button>
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("K1")}
                            >
                                K1
                            </button>    
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("L1")}
                            >
                                L1
                            </button>    
                        </td>
                        <td></td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("O1")}
                            >
                                O1
                            </button>    
                        </td>
                        <td></td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("R1")}
                            >
                                R1
                            </button>
                        </td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("X1")}
                            >
                                X1
                            </button>
                        </td>
                        <td></td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AA1")}
                            >
                                AA1
                            </button>        
                        </td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("B2")}
                            >
                                B2
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("C2")}
                            >
                                C2
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("E2")}
                            >
                                E2
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("F2")}
                            >
                                F2
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("H2")}
                            >
                                H2
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("I2")}
                            >
                                I2
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("K2")}
                            >
                                K2
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("L2")}
                            >
                                L2
                            </button>        
                        </td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("B3")}
                            >
                                B3
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("C3")}
                            >
                                C3
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("E3")}
                            >
                                E3
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("F3")}
                            >
                                F3
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("H3")}
                            >
                                H3
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("I3")}
                            >
                                I3
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("K3")}
                            >
                                K3
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("L3")}
                            >
                                L3
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("N3")}
                            >
                                N3
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("O3")}
                            >
                                O3
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("Q3")}
                            >
                                Q3
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("R3")}
                            >
                                R3
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("T3")}
                            >
                                T3
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("U3")}
                            >
                                U3
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("W3")}
                            >
                                W3
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("X3")}
                            >
                                X3
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("Z3")}
                            >
                                Z3
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AA3")}
                            >
                                AA3
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AC3")}
                            >
                                AC3
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AD3")}
                            >
                                AD3
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AF3")}
                            >
                                AF3
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AG3")}
                            >
                                AG3
                            </button>        
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("B4")}
                            >
                                B4
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("C4")}
                            >
                                C4
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("E4")}
                            >
                                E4
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("F4")}
                            >
                                F4
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("H4")}
                            >
                                H4
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("I4")}
                            >
                                I4
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("K4")}
                            >
                                K4
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("L4")}
                            >
                                L4
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("N4")}
                            >
                                N4
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("O4")}
                            >
                                O4
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("Q4")}
                            >
                                Q4
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("R4")}
                            >
                                R4
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("T4")}
                            >
                                T4
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("U4")}
                            >
                                U4
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("W4")}
                            >
                                W4
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("X4")}
                            >
                                X4
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("Z4")}
                            >
                                Z4
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AA4")}
                            >
                                AA4
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AC4")}
                            >
                                AC4
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AD4")}
                            >
                                AD4
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AF4")}
                            >
                                AF4
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AG4")}
                            >
                                AG4
                            </button>        
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("B5")}
                            >
                                B5
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("C5")}
                            >
                                C5
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("E5")}
                            >
                                E5
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("F5")}
                            >
                                F5
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("H5")}
                            >
                                H5
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("I5")}
                            >
                                I5
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("K5")}
                            >
                                K5
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("L5")}
                            >
                                L5
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("N5")}
                            >
                                N5
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("O5")}
                            >
                                O5
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("Q5")}
                            >
                                Q5
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("R5")}
                            >
                                R5
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("T5")}
                            >
                                T5
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("U5")}
                            >
                                U5
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("W5")}
                            >
                                W5
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("X5")}
                            >
                                X5
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("Z5")}
                            >
                                Z5
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AA5")}
                            >
                                AA5
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AC5")}
                            >
                                AC5
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AD5")}
                            >
                                AD5
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AF5")}
                            >
                                AF5
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AG5")}
                            >
                                AG5
                            </button>        
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>6</td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("B6")}
                            >
                                B6
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("C6")}
                            >
                                C6
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("E6")}
                            >
                                E6
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("F6")}
                            >
                                F6
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("H6")}
                            >
                                H6
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("I6")}
                            >
                                I6
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("K6")}
                            >
                                K6
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("L6")}
                            >
                                L6
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("N6")}
                            >
                                N6
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("O6")}
                            >
                                O6
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("Q6")}
                            >
                                Q6
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("R6")}
                            >
                                R6
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("T6")}
                            >
                                T6
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("U6")}
                            >
                                U6
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("W6")}
                            >
                                W6
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("X6")}
                            >
                                X6
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("Z6")}
                            >
                                Z6
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AA6")}
                            >
                                AA6
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AC6")}
                            >
                                AC6
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AD6")}
                            >
                                AD6
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AF6")}
                            >
                                AF6
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AG6")}
                            >
                                AG6
                            </button>        
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>7</td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("B7")}
                            >
                                B7
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("C7")}
                            >
                                C7
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("E7")}
                            >
                                E7
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("F7")}
                            >
                                F7
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("H7")}
                            >
                                H7
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("I7")}
                            >
                                I7
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("K7")}
                            >
                                K7
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("L7")}
                            >
                                L7
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("N7")}
                            >
                                N7
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("O7")}
                            >
                                O7
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("Q7")}
                            >
                                Q7
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("R7")}
                            >
                                R7
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("T7")}
                            >
                                T7
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("U7")}
                            >
                                U7
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("W7")}
                            >
                                W7
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("X7")}
                            >
                                X7
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("Z7")}
                            >
                                Z7
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AA7")}
                            >
                                AA7
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AC7")}
                            >
                                AC7
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AD7")}
                            >
                                AD7
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AF7")}
                            >
                                AF7
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AG7")}
                            >
                                AG7
                            </button>        
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>8</td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("B8")}
                            >
                                B8
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("B8")}
                            >
                                C8
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("E8")}
                            >
                                E8
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("F8")}
                            >
                                F8
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("H8")}
                            >
                                H8
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("I8")}
                            >
                                I8
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("K8")}
                            >
                                K8
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("L8")}
                            >
                                L8
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("N8")}
                            >
                                N8
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("O8")}
                            >
                                O8
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("Q8")}
                            >
                                Q8
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("R8")}
                            >
                                R8
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("T8")}
                            >
                                T8
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("U8")}
                            >
                                U8
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("W8")}
                            >
                                W8
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("X8")}
                            >
                                X8
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("Z8")}
                            >
                                Z8
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AA8")}
                            >
                                AA8
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AC8")}
                            >
                                AC8
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AD8")}
                            >
                                AD8
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AF8")}
                            >
                                AF8
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AG8")}
                            >
                                AG8
                            </button>        
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>9</td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("B9")}
                            >
                                B9
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("C9")}
                            >
                                C9
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("E9")}
                            >
                                E9
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("F9")}
                            >
                                F9
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("H9")}
                            >
                                H9
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("I9")}
                            >
                                I9
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("K9")}
                            >
                                K9
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("L9")}
                            >
                                L9
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("N9")}
                            >
                                N9
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("O9")}
                            >
                                O9
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("Q9")}
                            >
                                Q9
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("R9")}
                            >
                                R9
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("T9")}
                            >
                                T9
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("U9")}
                            >
                                U9
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("W9")}
                            >
                                W9
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("X9")}
                            >
                                X9
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("Z9")}
                            >
                                Z9
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AA9")}
                            >
                                AA9
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AC9")}
                            >
                                AC9
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AD9")}
                            >
                                AD9
                            </button>        
                        </td>
                        <td></td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AF9")}
                            >
                                AF9
                            </button>        
                        </td>
                        <td>
                            <button
                                onClick={()=>getzaseki("AG9")}
                            >
                                AG9
                            </button>        
                        </td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    );
};